### ISSUE TITLE
Heavy stutters on all streams RPi4 4GB

### ISSUE THREAD

**Issue by chkpwd** [OpenSurv/OpenSurv#29]
This stutter is not present on the UniFi Protect software nor in VLC when streaming all 6 cameras. 

**Config:**
```yaml
essentials:
  screens:
    - streams:
        - url: "rtsp://192.168.1.253:7447/blah"
          freeform_advanced_mpv_options: "--profile=low-latency --untimed"
        - url: "rtsp://192.168.1.253:7447/blah"
          freeform_advanced_mpv_options: "--profile=low-latency --untimed"
        - url: "rtsp://192.168.1.253:7447/blah"
          freeform_advanced_mpv_options: "--profile=low-latency --untimed"
        - url: "rtsp://192.168.1.253:7447/blah"
          freeform_advanced_mpv_options: "--profile=low-latency --untimed"
        - url: "rtsp://192.168.1.253:7447/blah"
          freeform_advanced_mpv_options: "--profile=low-latency --untimed"
        - url: "rtsp://192.168.1.253:7447/blah"
```

https://github.com/user-attachments/assets/29b80568-e535-44a5-bc87-4a68498aaa66

https://github.com/user-attachments/assets/3d1158df-f22b-4317-9b6c-3dd50b08f45c
